<?php

namespace BackOffice\RO\AgenceBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * agenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agenceRepository extends EntityRepository {

    public function loadAgenceForGrid() {
        $query = $this
                ->createQueryBuilder('a')
                ->select(array('a.id','a.nomAgence','a.cpAgence','a.villeAgence'))
                ->setFirstResult(0)
                ->setMaxResults(20);
        return $query;
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

}
