<?php

namespace BackOffice\RO\ContratBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * contratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contratRepository extends EntityRepository {

    public function loadContratForGrid() {
        $query = $this
                ->createQueryBuilder('c')
                ->select(array('c.id','c.numContrat'))
                ->setFirstResult(0)
                ->setMaxResults(20);
        return $query;
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

}
