<?php

namespace BackOffice\RO\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * reservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationRepository extends EntityRepository {

    public function loadReservationForGrid() {
        $query = $this
                ->createQueryBuilder('r')
                ->select(array('r.id','r.numReservation'))
                ->setFirstResult(0)
                ->setMaxResults(20);
        return $query;
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

}
