<?php

namespace BackOffice\RO\MarqueBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * marqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marqueRepository extends EntityRepository {

    public function loadMarqueForGrid() {
        $query = $this
                ->createQueryBuilder('e')
                ->select(array('e.id','e.nomMarque'))
                ->setFirstResult(0)
                ->setMaxResults(20);
        return $query;
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

}
