<?php

namespace BackOffice\RO\VehiculeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * vehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vehiculeRepository extends EntityRepository {

    public function loadVehiculeForGrid() {
        $query = $this
                ->createQueryBuilder('v')
                ->select('v')
                ->setFirstResult(0)
                ->setMaxResults(20);
        return $query;
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

    public function deleteVehiculeByModele($id) {
        $deletedVehicule = $this->createQueryBuilder("v")
                        ->delete()
                        ->where('v.modele  = :idModele')->setParameter("idModele", $id)
                        ->getQuery()->execute();

        return $deletedVehicule;
    }

}
