<?php

namespace BackOffice\RO\EntrepriseBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * entrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entrepriseRepository extends EntityRepository {

    public function loadEntrepriseForGrid() {
        $query = $this
                ->createQueryBuilder('e')
                ->select(array('e.id','e.nomEntreprise','e.cpEntreprise','e.villeEntreprise'))
                ->setFirstResult(0)
                ->setMaxResults(20);
        return $query;
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class || is_subclass_of($class, $this->getEntityName());
    }

}
